services:
  postgres:
    image: postgres:16
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPORT: ${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - shared_pg_data:/var/lib/postgresql/data
    networks:
      - microservices_net_acc_wlt_srv

volumes:
  shared_pg_data:

networks:
  microservices_net_acc_wlt_srv:
    name: microservices_net_acc_wlt_srv
